/*DROP TABLE TB_ESTATUS
DROP TABLE TB_USUARIO
DROP TABLE TB_MARCA
DROP TABLE TB_TIPO
DROP TABLE TB_ACTIVO
DROP TABLE TB_ROLL
DROP TABLE TB_CATEGORIA_ACTIVO
*/

CREATE TABLE TB_USUARIO(
     CODIGO INT PRIMARY KEY,
	 NOMBRE NVARCHAR(50),
	 ROLL INT,
	 USUARIO NVARCHAR(10),
	 PASS    NVARCHAR(10),
	 ESTATUS NVARCHAR(1)
)

CREATE TABLE TB_ROLL(
    COD_ROLL INT PRIMARY KEY,
	ROLL NVARCHAR(15)
)

CREATE TABLE TB_ESTATUS(
    ESTATUS NVARCHAR(1) PRIMARY KEY,
	DESCRIPCION NVARCHAR(20)
)

ALTER TABLE TB_USUARIO
ADD FOREIGN KEY (ROLL) REFERENCES TB_ROLL(COD_ROLL);


ALTER TABLE TB_USUARIO
ADD FOREIGN KEY (ESTATUS) REFERENCES TB_ESTATUS(ESTATUS);


CREATE TABLE TB_ACTIVO(
   COD_ACTIVO INT PRIMARY KEY,
   CAT_ACTIVO INT,
   USUARIO INT,
   TIPO INT, 
   MARCA INT, 
   SERIE NVARCHAR(25), 
   COLOR NVARCHAR(25),
   DESCRIPCION NVARCHAR(150),
   ESTATUS NVARCHAR(1)
)

CREATE TABLE TB_CATEGORIA_ACTIVO(
	CAT_ACTIVO INT PRIMARY KEY,
	ACTIVO NVARCHAR(20)
)

/*1 TECNOLOGÍA  2 MOBILIARIO*/
CREATE TABLE TB_TIPO(
   COD_TIPO INT PRIMARY KEY,
   TIPO NVARCHAR(20)
)

CREATE TABLE TB_MARCA(
    COD_MARCA INT PRIMARY KEY,
	MARCA NVARCHAR(20)
)


ALTER TABLE TB_ACTIVO
ADD FOREIGN KEY (CAT_ACTIVO) REFERENCES TB_CATEGORIA_ACTIVO(CAT_ACTIVO);

ALTER TABLE TB_ACTIVO
ADD FOREIGN KEY (TIPO) REFERENCES TB_TIPO(COD_TIPO);

ALTER TABLE TB_ACTIVO
ADD FOREIGN KEY (MARCA) REFERENCES TB_MARCA(COD_MARCA);

ALTER TABLE TB_ACTIVO
ADD FOREIGN KEY (USUARIO) REFERENCES TB_USUARIO(CODIGO);

